### ISSUE TITLE
partials ?

### ISSUE THREAD

**Issue by smeevil** [slime-lang/phoenix_slime#7] opened 2015-09-21 09:27 UTC
Hi,

I was wondering if there is already support for rendering partials ?

/Gerard

**Comment by doomspork** [comment] 2015-09-21 15:08
Hi @smeevil, it should be supported.  PhoenixSlim (and SlimFast) translate Slim to EEx and rely on EEx to handle the bulk of the work, rendering partial should work so long as the appropriate EEx is generated.

Are you having problems?  If so you might have encountered a bug.

**Comment by smeevil** [comment] 2015-09-22 09:30
As soon as i try to
`= render "_nav.html"`
it returns 
`** (CompileError) web/views/layout_view.ex:1: imported Phoenix.Controller.render/1 conflicts with local function`

**Comment by doomspork** [comment] 2015-09-22 15:15
Hi @smeevil do you have a sample project I could look at?  I'm wondering if something is being included that doesn't need to be, PhoenixSlim is no different from Chris McCord's [PhoenixHaml](https://github.com/chrismccord/phoenix_haml).

In addition to the `config/config.exs` updates for PhoenixSlim, are you also including `using SlimFast`?

**Comment by smeevil** [comment] 2015-09-23 10:02
The error only seems to pop up when using the render in a layout (templates/layout/app.html.slim)
If I use it in a "normal" template, it does work O.o
Can you confirm this as well ?

**Comment by doomspork** [comment] 2015-09-24 16:43
@smeevil that's interesting and not something I have experienced.  

I'm hoping to set some time aside this week to put together a sample Phoenix + PhoenixSlim project which I hope allow me to repo this issue.  I'll ping you on the repo so you can give me feedback on setting up your scenario.

**Comment by doomspork** [comment] 2015-10-07 03:30
Hi @smeevil, sorry for the delay I've been very busy.  

I have put together a sample project at [doomspork/phoenix_slim_example](https://github.com/doomspork/phoenix_slim_example), can you take a look at it?  I tried to reproduce your issue in the layout [here](https://github.com/doomspork/phoenix_slim_example/blob/master/web/templates/layout/app.html.slim#L18) but everything appears to be working.

**Comment by doomspork** [comment] 2015-10-09 20:27
@smeevil have you had an opportunity to check out the sample project?  

What version of Elixir and Phoenix are you using btw?

**Comment by doomspork** [comment] 2015-10-14 15:50
I'm closing this for now because it appears to not be an issue.  @smeevil please let me know otherwise!

Thanks

**Closed as completed by doomspork** 2015-10-14 15:50 UTC

**Comment by smeevil** [comment] 2015-11-06 09:42
Hi man,

Sorry for the horrible late update, but actually working on several phoenix projects now and got a bit busy.

I did not encounter the error in any of the other projects, so i finally got some time to return to this one and found the problem :)

In the layout view I accidentally had both :
`use MyApp.Web, :view`
and 
`use MyApp.Web, :controller`

This was the cause of the problem, removing the controller fixed it.
So in the end, as usual, my bad :)

Nothing to see here, Carry on now !

**Comment by doomspork** [comment] 2015-11-06 15:30
Thanks for the follow-up @smeevil, glad things are working! :+1:
